version: "3"

services:
  modex_visualization:
    build:
      context: .
      dockerfile: Dockerfile
    image: modex_visualization
    container_name: modex_visualization
    env_file:
      - ./.envs/.production/.dash
    expose:
    - 80
    restart: always
    networks:
    - caddy_network
    - modex_visualization

  redis:
    image: redis:6.2
    networks:
    - modex_visualization


networks:
  modex_visualization:
  caddy_network:
    external:
      name: docker_caddy_network
