version: "3"

volumes:
  production_postgres_data: {}

services:
  modex_visualization:
    build:
      context: .
      dockerfile: Dockerfile
    image: modex_visualization
    container_name: modex_visualization
    env_file:
      - ./.envs/.production/.dash
    expose:
    - 80
    depends_on:
     - postgres
    restart: always
    networks:
    - caddy_network
    - modex_visualization

  redis:
    image: redis:6.2
    networks:
    - modex_visualization

  postgres:
    image: postgres:13.2-alpine
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.production/.postgres
    networks:
    - modex_visualization

networks:
  modex_visualization:
  caddy_network:
    external:
      name: docker_caddy_network
